"""
Base Model with Timestamps
Generated by sqlmodel-schema-designer skill

Provides a reusable mixin for common timestamp fields.
"""

from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class TimestampMixin(SQLModel):
    """
    Mixin providing created_at and updated_at timestamps.

    Inherit from this class to add automatic timestamps to models.
    """
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Record creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Last update timestamp"
    )


class BaseModel(TimestampMixin):
    """
    Base model with ID and timestamps.

    Inherit from this for models that need:
    - Primary key ID
    - created_at timestamp
    - updated_at timestamp

    Note: Don't set table=True on this class.
    Set it on the child class.
    """
    id: Optional[int] = Field(
        default=None,
        primary_key=True,
        description="Unique identifier"
    )


# Example usage:
#
# class Task(BaseModel, table=True):
#     __tablename__ = "tasks"
#
#     title: str = Field(max_length=255)
#     user_id: int = Field(foreign_key="users.id", index=True)
