"""
Async Database Configuration
Generated by sqlmodel-schema-designer skill

Provides async engine, session factory, and utilities for SQLModel.
"""

import os
from contextlib import asynccontextmanager
from typing import AsyncGenerator

from sqlmodel import SQLModel
from sqlmodel.ext.asyncio.session import AsyncSession
from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker
from sqlalchemy import text


# ============================================================
# Configuration
# ============================================================

DATABASE_URL = os.getenv(
    "DATABASE_URL",
    "postgresql+asyncpg://postgres:postgres@localhost:5432/todoapp"
)

# For Neon PostgreSQL, ensure SSL is enabled:
# DATABASE_URL=postgresql+asyncpg://user:pass@ep-xxx.neon.tech/db?sslmode=require


# ============================================================
# Engine Setup
# ============================================================

engine = create_async_engine(
    DATABASE_URL,
    echo=os.getenv("DB_ECHO", "false").lower() == "true",  # SQL logging
    pool_pre_ping=True,      # Check connection health before use
    pool_size=5,             # Connection pool size
    max_overflow=10,         # Max overflow connections
)


# ============================================================
# Session Factory
# ============================================================

async_session = async_sessionmaker(
    engine,
    class_=AsyncSession,
    expire_on_commit=False,  # Don't expire objects after commit
)


# ============================================================
# Dependency for FastAPI
# ============================================================

async def get_session() -> AsyncGenerator[AsyncSession, None]:
    """
    FastAPI dependency that yields a database session.

    Usage:
        @app.get("/tasks")
        async def get_tasks(session: AsyncSession = Depends(get_session)):
            ...
    """
    async with async_session() as session:
        yield session


# ============================================================
# Database Lifecycle
# ============================================================

async def create_db_and_tables() -> None:
    """
    Create all tables defined in SQLModel metadata.

    Call this on application startup.
    """
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.create_all)


async def drop_db_and_tables() -> None:
    """
    Drop all tables. USE WITH CAUTION.

    Only for testing/development.
    """
    async with engine.begin() as conn:
        await conn.run_sync(SQLModel.metadata.drop_all)


# ============================================================
# Health Check
# ============================================================

async def check_database_health() -> bool:
    """
    Check if database is reachable.

    Returns:
        True if database responds, False otherwise.
    """
    try:
        async with async_session() as session:
            await session.exec(text("SELECT 1"))
            return True
    except Exception:
        return False


# ============================================================
# FastAPI Lifespan Integration
# ============================================================

@asynccontextmanager
async def db_lifespan(app):
    """
    Database lifespan manager for FastAPI.

    Usage:
        app = FastAPI(lifespan=db_lifespan)
    """
    # Startup: Create tables
    await create_db_and_tables()
    yield
    # Shutdown: Dispose engine
    await engine.dispose()


# ============================================================
# Example Usage in FastAPI
# ============================================================
#
# from contextlib import asynccontextmanager
# from fastapi import FastAPI, Depends
# from sqlmodel.ext.asyncio.session import AsyncSession
#
# from app.database import db_lifespan, get_session
# from app.models import Task
#
# app = FastAPI(lifespan=db_lifespan)
#
# @app.get("/tasks")
# async def get_tasks(session: AsyncSession = Depends(get_session)):
#     result = await session.exec(select(Task))
#     return result.all()
