"""
Task Model
Generated by sqlmodel-schema-designer skill

Task model with user relationship for multi-user isolation.
"""

from datetime import datetime
from typing import Optional, TYPE_CHECKING
from sqlmodel import SQLModel, Field, Relationship

if TYPE_CHECKING:
    from .user import User


# ============================================================
# Base Schema (shared fields)
# ============================================================

class TaskBase(SQLModel):
    """Base task fields shared across schemas."""
    title: str = Field(
        min_length=1,
        max_length=255,
        description="Task title"
    )
    description: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional task description"
    )
    is_completed: bool = Field(
        default=False,
        description="Task completion status"
    )


# ============================================================
# Database Model (table=True)
# ============================================================

class Task(TaskBase, table=True):
    """Task database model with user relationship."""
    __tablename__ = "tasks"

    id: Optional[int] = Field(default=None, primary_key=True)

    # Foreign key for user isolation
    user_id: int = Field(
        foreign_key="users.id",
        index=True,
        description="Owner user ID"
    )

    # Timestamps
    created_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Creation timestamp"
    )
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        description="Last update timestamp"
    )

    # Relationship to user
    user: Optional["User"] = Relationship(back_populates="tasks")


# ============================================================
# Input Schemas
# ============================================================

class TaskCreate(TaskBase):
    """
    Schema for creating a new task.

    Note: user_id is set from authenticated user, not from request body.
    """
    pass


class TaskUpdate(SQLModel):
    """Schema for updating a task (all fields optional)."""
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    is_completed: Optional[bool] = None


# ============================================================
# Output Schemas
# ============================================================

class TaskRead(TaskBase):
    """Schema for reading task data (API responses)."""
    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime


class TaskReadWithUser(TaskRead):
    """Schema for reading task with user info."""
    user: Optional["UserRead"] = None


# Forward reference for UserRead
from .user import UserRead
TaskReadWithUser.model_rebuild()
