"""
User Model
Generated by sqlmodel-schema-designer skill

Complete user model with authentication fields and relationships.
"""

from datetime import datetime
from typing import Optional, List, TYPE_CHECKING
from sqlmodel import SQLModel, Field, Relationship

if TYPE_CHECKING:
    from .task import Task


# ============================================================
# Base Schema (shared fields)
# ============================================================

class UserBase(SQLModel):
    """Base user fields shared across schemas."""
    email: str = Field(
        unique=True,
        index=True,
        max_length=255,
        description="User email address"
    )
    username: str = Field(
        unique=True,
        index=True,
        min_length=3,
        max_length=50,
        description="Unique username"
    )


# ============================================================
# Database Model (table=True)
# ============================================================

class User(UserBase, table=True):
    """User database model."""
    __tablename__ = "users"

    id: Optional[int] = Field(default=None, primary_key=True)
    hashed_password: str = Field(description="Bcrypt hashed password")
    is_active: bool = Field(default=True, description="Account active status")
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # Relationships
    tasks: List["Task"] = Relationship(back_populates="user")


# ============================================================
# Input Schemas
# ============================================================

class UserCreate(UserBase):
    """Schema for creating a new user."""
    password: str = Field(
        min_length=8,
        max_length=100,
        description="Plain text password (will be hashed)"
    )


class UserUpdate(SQLModel):
    """Schema for updating user (all fields optional)."""
    username: Optional[str] = Field(default=None, min_length=3, max_length=50)
    email: Optional[str] = Field(default=None, max_length=255)


class UserPasswordUpdate(SQLModel):
    """Schema for changing password."""
    current_password: str
    new_password: str = Field(min_length=8, max_length=100)


# ============================================================
# Output Schemas
# ============================================================

class UserRead(UserBase):
    """Schema for reading user data (API responses)."""
    id: int
    is_active: bool
    created_at: datetime


class UserReadWithTasks(UserRead):
    """Schema for reading user with their tasks."""
    tasks: List["TaskRead"] = []


# Forward reference for TaskRead
from .task import TaskRead
UserReadWithTasks.model_rebuild()
