"""
FastAPI Authentication Dependencies
Generated by jwt-auth-integrator skill
"""

from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer
from sqlmodel.ext.asyncio.session import AsyncSession

from app.database import get_session
from app.models.user import User
from app.auth import verify_token

# OAuth2 scheme for token extraction
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="auth/login")


async def get_current_user(
    token: str = Depends(oauth2_scheme),
    session: AsyncSession = Depends(get_session)
) -> User:
    """
    Extract and validate current user from JWT token.

    This dependency:
    1. Extracts the Bearer token from Authorization header
    2. Verifies and decodes the JWT
    3. Fetches the user from database
    4. Returns the user object

    Args:
        token: JWT token from Authorization header.
        session: Database session.

    Returns:
        Current authenticated User object.

    Raises:
        HTTPException: 401 if token is invalid or user not found.
    """
    credentials_exception = HTTPException(
        status_code=status.HTTP_401_UNAUTHORIZED,
        detail="Could not validate credentials",
        headers={"WWW-Authenticate": "Bearer"},
    )

    # Verify token
    payload = verify_token(token)
    if payload is None:
        raise credentials_exception

    # Extract user ID
    user_id = payload.get("sub")
    if user_id is None:
        raise credentials_exception

    # Fetch user from database
    user = await session.get(User, int(user_id))
    if user is None:
        raise credentials_exception

    return user


async def get_current_active_user(
    current_user: User = Depends(get_current_user)
) -> User:
    """
    Ensure the current user is active.

    Args:
        current_user: User from get_current_user dependency.

    Returns:
        Active User object.

    Raises:
        HTTPException: 403 if user is inactive.
    """
    if not current_user.is_active:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail="Inactive user"
        )
    return current_user
