"""
User Model and Schemas
Generated by jwt-auth-integrator skill
"""

from datetime import datetime
from typing import Optional

from pydantic import EmailStr, validator
from sqlmodel import SQLModel, Field


class UserBase(SQLModel):
    """Base user fields shared across schemas."""
    email: str = Field(unique=True, index=True)
    username: str = Field(unique=True, index=True, min_length=3, max_length=50)


class User(UserBase, table=True):
    """User database model."""
    __tablename__ = "users"

    id: Optional[int] = Field(default=None, primary_key=True)
    hashed_password: str
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class UserCreate(UserBase):
    """Schema for user registration."""
    password: str = Field(min_length=8, max_length=100)

    @validator("password")
    def password_strength(cls, v):
        """Validate password strength."""
        if len(v) < 8:
            raise ValueError("Password must be at least 8 characters")
        if not any(c.isupper() for c in v):
            raise ValueError("Password must contain at least one uppercase letter")
        if not any(c.islower() for c in v):
            raise ValueError("Password must contain at least one lowercase letter")
        if not any(c.isdigit() for c in v):
            raise ValueError("Password must contain at least one digit")
        return v

    @validator("email")
    def email_valid(cls, v):
        """Validate email format."""
        if "@" not in v:
            raise ValueError("Invalid email format")
        return v.lower()


class UserRead(UserBase):
    """Schema for reading user data (API responses)."""
    id: int
    is_active: bool
    created_at: datetime


class UserUpdate(SQLModel):
    """Schema for updating user data."""
    username: Optional[str] = Field(default=None, min_length=3, max_length=50)
    email: Optional[str] = None


class Token(SQLModel):
    """JWT token response schema."""
    access_token: str
    token_type: str = "bearer"


class TokenData(SQLModel):
    """Token payload data."""
    user_id: Optional[int] = None
