#!/usr/bin/env python3
"""
SQLModel Model Generator
========================
Generates SQLModel model files with Base/Create/Read/Update schemas.

Usage:
    python generate_model.py <ModelName> [--output-dir <path>] [--with-user]

Examples:
    python generate_model.py Task
    python generate_model.py Task --output-dir backend/app/models
    python generate_model.py Project --with-user
"""

import argparse
import re
from pathlib import Path


def to_pascal_case(name: str) -> str:
    """Convert to PascalCase, preserving existing PascalCase."""
    if re.match(r'^[A-Z][a-zA-Z0-9]*$', name):
        return name
    parts = re.split(r'[-_]', name)
    return ''.join(word.capitalize() for word in parts if word)


def to_snake_case(name: str) -> str:
    """Convert PascalCase to snake_case."""
    result = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', result).lower()


def pluralize(name: str) -> str:
    """Simple pluralization."""
    if name.endswith('y'):
        return name[:-1] + 'ies'
    elif name.endswith(('s', 'x', 'z', 'ch', 'sh')):
        return name + 'es'
    return name + 's'


MODEL_TEMPLATE = '''"""
__NAME__ Model
Generated by sqlmodel-schema-designer skill
"""

from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field__RELATIONSHIP_IMPORT__


# ============================================================
# Base Schema (shared fields)
# ============================================================

class __NAME__Base(SQLModel):
    """Base __name__ fields shared across schemas."""
    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    # Add more fields as needed


# ============================================================
# Database Model (table=True)
# ============================================================

class __NAME__(__NAME__Base, table=True):
    """__NAME__ database model."""
    __tablename__ = "__table_name__"

    id: Optional[int] = Field(default=None, primary_key=True)
__USER_FIELD__
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
__RELATIONSHIP__

# ============================================================
# Input Schemas
# ============================================================

class __NAME__Create(__NAME__Base):
    """Schema for creating a new __name__."""
    pass


class __NAME__Update(SQLModel):
    """Schema for updating __name__ (all fields optional)."""
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    # Add more optional fields as needed


# ============================================================
# Output Schemas
# ============================================================

class __NAME__Read(__NAME__Base):
    """Schema for reading __name__ data (API responses)."""
    id: int
__USER_ID_READ__    created_at: datetime
    updated_at: datetime
'''


def generate_model(
    model_name: str,
    output_dir: str = ".",
    with_user: bool = False
) -> dict[str, str]:
    """Generate model file."""
    name = to_pascal_case(model_name)
    snake_name = to_snake_case(name)
    table_name = pluralize(snake_name)

    content = MODEL_TEMPLATE
    content = content.replace("__NAME__", name)
    content = content.replace("__name__", snake_name)
    content = content.replace("__table_name__", table_name)

    if with_user:
        content = content.replace("__RELATIONSHIP_IMPORT__", ", Relationship")
        content = content.replace(
            "__USER_FIELD__",
            "    user_id: int = Field(foreign_key=\"users.id\", index=True)\n"
        )
        content = content.replace(
            "__RELATIONSHIP__",
            "\n    # Relationship to user\n    user: Optional[\"User\"] = Relationship(back_populates=\"" + table_name + "\")"
        )
        content = content.replace("__USER_ID_READ__", "    user_id: int\n")
    else:
        content = content.replace("__RELATIONSHIP_IMPORT__", "")
        content = content.replace("__USER_FIELD__", "")
        content = content.replace("__RELATIONSHIP__", "")
        content = content.replace("__USER_ID_READ__", "")

    # Create output path
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)

    model_file = output_path / f"{snake_name}.py"
    model_file.write_text(content)

    return {
        "model_file": str(model_file),
        "model_name": name,
        "table_name": table_name,
        "with_user": with_user,
    }


def main():
    parser = argparse.ArgumentParser(description="Generate SQLModel model")
    parser.add_argument("model", help="Model name (e.g., Task, Project)")
    parser.add_argument("--output-dir", "-o", default=".", help="Output directory")
    parser.add_argument("--with-user", "-u", action="store_true",
                        help="Add user_id foreign key and relationship")

    args = parser.parse_args()

    result = generate_model(args.model, args.output_dir, args.with_user)

    print(f"Generated SQLModel '{result['model_name']}':")
    print(f"  File: {result['model_file']}")
    print(f"  Table: {result['table_name']}")
    print(f"  User relation: {'Yes' if result['with_user'] else 'No'}")
    print()
    print("Next steps:")
    print("  1. Add/modify fields in the Base schema")
    print("  2. Update the Update schema with optional fields")
    print("  3. Import model in __init__.py")
    if result['with_user']:
        print("  4. Add back_populates to User model")


if __name__ == "__main__":
    main()
