#!/usr/bin/env python3
"""
CRUD Generator Script
=====================
Generates FastAPI CRUD routes and SQLModel models from a resource name.

Usage:
    python generate_crud.py <resource_name> [--output-dir <path>]

Examples:
    python generate_crud.py task
    python generate_crud.py task --output-dir backend/app
    python generate_crud.py project --output-dir src
"""

import argparse
import os
from pathlib import Path


def to_pascal_case(name: str) -> str:
    """Convert snake_case to PascalCase."""
    return "".join(word.capitalize() for word in name.split("_"))


def to_snake_case(name: str) -> str:
    """Ensure name is in snake_case."""
    return name.lower().replace("-", "_")


def pluralize(name: str) -> str:
    """Simple pluralization."""
    if name.endswith("y"):
        return name[:-1] + "ies"
    elif name.endswith(("s", "x", "z", "ch", "sh")):
        return name + "es"
    return name + "s"


ROUTE_TEMPLATE = '''"""
{Resource} CRUD Routes
Generated by fastapi-crud-generator skill
"""

from fastapi import APIRouter, Depends, HTTPException, status
from sqlmodel import select
from sqlmodel.ext.asyncio.session import AsyncSession

from app.database import get_session
from app.auth import get_current_user
from app.models.user import User
from app.models.{resource} import {Resource}, {Resource}Create, {Resource}Read, {Resource}Update

router = APIRouter(prefix="/{resources}", tags=["{Resources}"])


@router.get("", response_model=list[{Resource}Read])
async def list_{resources}(
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """List all {resources} for the current user."""
    statement = select({Resource}).where({Resource}.user_id == current_user.id)
    result = await session.exec(statement)
    return result.all()


@router.get("/{{id}}", response_model={Resource}Read)
async def get_{resource}(
    id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Get a specific {resource} by ID."""
    {resource} = await session.get({Resource}, id)
    if not {resource}:
        raise HTTPException(status_code=404, detail="{Resource} not found")
    if {resource}.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")
    return {resource}


@router.post("", response_model={Resource}Read, status_code=status.HTTP_201_CREATED)
async def create_{resource}(
    {resource}_in: {Resource}Create,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Create a new {resource}."""
    {resource} = {Resource}(**{resource}_in.model_dump(), user_id=current_user.id)
    session.add({resource})
    await session.commit()
    await session.refresh({resource})
    return {resource}


@router.put("/{{id}}", response_model={Resource}Read)
async def update_{resource}(
    id: int,
    {resource}_in: {Resource}Update,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Update a {resource}."""
    {resource} = await session.get({Resource}, id)
    if not {resource}:
        raise HTTPException(status_code=404, detail="{Resource} not found")
    if {resource}.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")

    update_data = {resource}_in.model_dump(exclude_unset=True)
    for key, value in update_data.items():
        setattr({resource}, key, value)

    session.add({resource})
    await session.commit()
    await session.refresh({resource})
    return {resource}


@router.delete("/{{id}}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_{resource}(
    id: int,
    current_user: User = Depends(get_current_user),
    session: AsyncSession = Depends(get_session),
):
    """Delete a {resource}."""
    {resource} = await session.get({Resource}, id)
    if not {resource}:
        raise HTTPException(status_code=404, detail="{Resource} not found")
    if {resource}.user_id != current_user.id:
        raise HTTPException(status_code=403, detail="Not authorized")

    await session.delete({resource})
    await session.commit()
'''


MODEL_TEMPLATE = '''"""
{Resource} SQLModel Models
Generated by fastapi-crud-generator skill
"""

from datetime import datetime
from typing import Optional
from sqlmodel import SQLModel, Field


class {Resource}Base(SQLModel):
    """Base {resource} fields."""
    title: str = Field(min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    is_completed: bool = Field(default=False)


class {Resource}({Resource}Base, table=True):
    """Database model."""
    __tablename__ = "{resources}"

    id: Optional[int] = Field(default=None, primary_key=True)
    user_id: int = Field(foreign_key="users.id", index=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class {Resource}Create({Resource}Base):
    """Create schema."""
    pass


class {Resource}Read({Resource}Base):
    """Read schema."""
    id: int
    user_id: int
    created_at: datetime
    updated_at: datetime


class {Resource}Update(SQLModel):
    """Update schema (partial)."""
    title: Optional[str] = Field(default=None, min_length=1, max_length=255)
    description: Optional[str] = Field(default=None, max_length=1000)
    is_completed: Optional[bool] = None
'''


def generate_crud(resource_name: str, output_dir: str = ".") -> dict[str, str]:
    """Generate CRUD files for a resource."""
    resource = to_snake_case(resource_name)
    Resource = to_pascal_case(resource)
    resources = pluralize(resource)
    Resources = to_pascal_case(resources)

    replacements = {
        "{resource}": resource,
        "{Resource}": Resource,
        "{resources}": resources,
        "{Resources}": Resources,
    }

    route_content = ROUTE_TEMPLATE
    model_content = MODEL_TEMPLATE

    for old, new in replacements.items():
        route_content = route_content.replace(old, new)
        model_content = model_content.replace(old, new)

    # Fix FastAPI path parameters: {{id}} -> {id}
    route_content = route_content.replace("{{id}}", "{id}")

    # Create output paths
    output_path = Path(output_dir)
    routes_dir = output_path / "routes"
    models_dir = output_path / "models"

    routes_dir.mkdir(parents=True, exist_ok=True)
    models_dir.mkdir(parents=True, exist_ok=True)

    route_file = routes_dir / f"{resource}.py"
    model_file = models_dir / f"{resource}.py"

    # Write files
    route_file.write_text(route_content)
    model_file.write_text(model_content)

    return {
        "route_file": str(route_file),
        "model_file": str(model_file),
    }


def main():
    parser = argparse.ArgumentParser(description="Generate FastAPI CRUD endpoints")
    parser.add_argument("resource", help="Resource name (e.g., task, project)")
    parser.add_argument("--output-dir", "-o", default=".", help="Output directory")

    args = parser.parse_args()

    files = generate_crud(args.resource, args.output_dir)

    print(f"Generated CRUD for '{args.resource}':")
    print(f"  Routes: {files['route_file']}")
    print(f"  Models: {files['model_file']}")
    print("\nNext steps:")
    print("  1. Review and customize the generated files")
    print("  2. Add the router to your FastAPI app")
    print("  3. Run database migrations if needed")


if __name__ == "__main__":
    main()
